spring.application.name=job
server.port=8082

#DataSource - PostgreSQL
spring.datasource.url=${JOB_DATABASE_URL:jdbc:postgresql://localhost:5432/job_db}
spring.datasource.username=${JOB_DATABASE_USERNAME:postgres}
spring.datasource.password=${JOB_DATABASE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
# The schema is created by database/job_db.sql, so Hibernate does not touch it.
# Use "update" instead if you want Hibernate to create/alter the tables itself.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

#Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
